services:
  postgres:
    image: postgres:16
    container_name: eventreservation-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_PASSWORD: ${API_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: eventreservation-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management Web UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_listener", "5672"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: eventreservation-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Container"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=eventreservation;Username=api;Password=${API_PASSWORD}"
      RabbitMQ__HostName: ${RABBITMQ_HOST}
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
      RabbitMQ__Port: 5672
    ports:
      - "5045:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres-data: